name: Update external sources

# Controls when the action will run.
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '54 */4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_NAME: '${{ secrets.GIT_NAME }}'
  GIT_EMAIL: '${{ secrets.GIT_EMAIL }}'
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

jobs:
  scheduler:
    name: Trigger action
    runs-on: '${{ matrix.os }}'

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.11'
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@main #Obviously yet another american...
        name: Clone repository
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install requirements
        run: |
          sudo bash "${{ github.workspace }}/scripts/dependencies.sh"

      - name: Install mypdns
        run: |
          pip install --no-cache mypdns

      - name: Import IP based blacklists
        run: bash "${{ github.workspace }}/scripts/import.sh"

      - name: Download and convert dumb hosts to plain data
        run: php -f  "${{ github.workspace }}/scripts/converter.php"

      - name: Update active list
        run: bash "${{ github.workspace }}/scripts/update_active_lists.sh"

      - name: Commit changes
        run: |
          tag=$(date +'day: %j of year %Y %H:%M:%S')
          git config --local user.email "$GIT_EMAIL"
          git config --local user.name "$GIT_NAME"
          git commit -m "Committed new lists $tag" -a
          git pull --rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
